=== alexvoipnsk/voiptest/opt/megaco/parser/schema/config.json
{
	"$schema" : "http://json-schema.org/draft-04/schema#",
	"title" : "Config file schema",
	"type" : "object",
	"properties" : {
		"LogDirectory" : {"type" : "string", "minLength" : 1},
		"Globals" : {
		    "type" : "object", 
		    "patternProperties" : {
		    	"^[a-zA-Z0-9_]+$" : {"type" : "string", "minLength" : 1}
		    },
		    "additionalProperties": false
	    },
	    "Dialplans" : {
	    	"type" : "array", 
	    	"items" : {"type" : "string", "minLength" : 1}
	    },
	    "Connections" : {
	    	"type" : "array",
	    	"items" : {
	    		"type" : "object",
	    		"properties" : {
	    			"id" : {"type" : "integer", "minimum" : 0, "exclusiveMinimum" : false},
	    			"name" : {"type" : "string", "minLength" : 1},
	    			"from_sock" : {"type" : "integer", "minimum" : 0, "exclusiveMinimum" : false},
	    			"to_sock" : {"type" : "integer", "minimum" : 0, "exclusiveMinimum" : false}
	    		},
	    		"required" : ["id", "name", "from_sock", "to_sock"]
	    	}
	    },
	    "sock" : {
	    	"type" : "array",
	    	"items" : {
	    		"type": "object", 
	    		"properties" : {
	    			"id" : {"type" : "integer", "minimum" : 0, "exclusiveMinimum" : false},
	    			"name" : {"type" : "string", "minLength" : 1},
	    			"ipaddr" : {"type" : "string", "pattern" : "^(([1-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){1}(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){2}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$"},
	    			"port" : {"type" : "integer", "minimum" : 1000, "maximum" : 65536, "exclusiveMinimum" : false, "exclusiveMaximum" : false},
	    			"transport" : {"type" : "string", "minLength" : 3},
	    			"proto" : {"type" : "string", "minLength" : 3},
	    			"profile": {"type" : "integer", "minimum" : 0, "exclusiveMinimum" : false},
	    			"network_buffer" : {"type" : "integer", "minimum" : 1000, "exclusiveMinimum" : false}
	    		},
	    		"required" : ["id", "ipaddr", "port", "transport", "proto", "profile"]
	    	}
	    },
	    "users" : {
	    	"type": "array", 
	    	"items": {
	    		"type": "object", 
	    		"properties": {
	    			"id": {"type" : "integer", "minimum" : 0, "exclusiveMinimum" : false},
	    			"username": {"type": "string", "minLength": 1, "maxLength": 255}, 
	    			"authname": {"type": "string", "minLength": 1, "maxLength": 255}, 
	    			"password": {"type": "string", "minLength": 1, "maxLength": 63}, 
	    			"domain": {"type": "string", "minLength": 1, "maxLength": 255},
	    			"service": {
	    				"type" : "array",
	    				"items" : {"type" : "string", "minLength" : 1},
	    			"servicelist": {
	    				"type" : "array",
	    				"items" : {"type" : "string", "minLength" : 1}	    			
	    			}
	    		},
	    		"required" : ["id", "username"]
	    	}
	    },
	    "trunks" : {
	    	"type": "array", 
	    	"items": {
	    		"type": "object", 
	    		"properties": {
	    			"id": {"type" : "integer", "minimum" : 0, "exclusiveMinimum" : false},
	    			"number": {"type" : "integer", "minimum" : 0, "exclusiveMinimum" : false},
	    			"name": {"type": "string", "minLength": 1, "maxLength": 255}, 
	    			"authname": {"type": "string", "minLength": 1, "maxLength": 255}, 
	    			"password": {"type": "string", "minLength": 1, "maxLength": 63}, 
	    			"domain": {"type": "string", "minLength": 1, "maxLength": 255}
	    			}
	    		},
	    		"required" : ["id", "name"]
	    	}
	    },
	    "device": {
	    	"type": "array", 
	    	"items": {
	    		"type": "object", 
	    		"properties": {
	    			"id": {"type" : "integer", "minimum" : 0, "exclusiveMinimum" : false},
	    			"type": {"type": "string", "minLength": 1, "maxLength": 15}, 
	    			"sw": {"type": "string", "minLength": 1, "maxLength": 15}, 
	    			"proto": {"type": "string", "minLength": 1, "maxLength": 15}, 
	    			"ipaddr": {"type": "string", "minLength": 7, "maxLength": 15}, 
	    			"port": {"type": "integer", "minimum": 1, "maximum": 65535}, 
	    			"login": {"type": "string", "minLength": 1, "maxLength": 255}, 
	    			"password": {"type": "string", "minLength": 1, "maxLength": 63}
	    		},
	    		"required" : ["id", "ipaddr", "port", "login"]
	    	}
	    },
	    "sigtran": {
	    	"type": "array", 
	    	"items": {
	    		"type": "object", 
	    		"properties": {
	    			"id": {"type" : "integer", "minimum" : 0, "exclusiveMinimum" : false},
	    			"asp": {
	    				"type" : "array",
	    				"items" : {"type" : "string", "minLength" : 1}
	    			},
	    			"iid": {
	    				"type" : "array",
	    				"items" : {"type" : "string", "minLength" : 1}
	    			}
	    		},
	    		"required" : ["id"]
	    	}
	    },
	    "sorm" : {
	    	"type" : "array",
	    	"items" : {
	    		"type" : "object",
	    		"properties" : {
	    			"id" : {"type" : "integer", "minimum" : 0, "exclusiveMinimum" : false},
	    			"ormNum" : {"type": "integer", "minimum": 0, "maximum": 255},
	    			"password" : {"type": "integer", "minimum": 0, "maximum": 999999},
	    			"version": {"type": "string", "minLength": 1, "maxLength": 255}, 
	    			"station_type": {"type": "string", "minLength": 1, "maxLength": 255}
	    		},
	    		"required" : ["id", "ormNum", "password", "version", "station_type"]
	    	}
	    },
	    "mgcp" : {
	    	"type" : "array",
	    	"items" : {
	    		"type" : "object",
	    		"properties" : {
	    			"id" : {"type" : "integer", "minimum" : 0, "exclusiveMinimum" : false},
	    			"mid" : {"type" : "string", "minLength" : 1},
	    			"encoding" : {"type" : "string", "enum" : ["full_text", "compact_text"]},
	    			"terms" : {
	    				"type" : "array",
	    				"items" : {"type" : "string", "minLength" : 1}
	    			}
	    		},
	    		"required" : ["id", "mid"]
	    	}
	    },
	    "megaco" : {
	    	"type" : "array",
	    	"items" : {
	    		"type" : "object",
	    		"properties" : {
	    			"id" : {"type" : "integer", "minimum" : 0, "exclusiveMinimum" : false},
	    			"mid" : {"type" : "string", "minLength" : 1},
	    			"encoding" : {"type" : "string", "enum" : ["full_text", "compact_text"]},
	    			"terms" : {
	    				"type" : "array",
	    				"items" : {"type" : "string", "minLength" : 1}
	    			}
	    		},
	    		"required" : ["id", "mid"]
	    	}
	    }
    },
	"required" : ["LogDirectory"]
}

=== alexvoipnsk/voiptest/tests/scripts/ag_mgcp/config.json
{
    "LogDirectory" : "/home/alexander/py_autotest/log/mgcp/",
    "Connections" : [
         {
              "id" : 0,
              "name" : "Link between Call Agent and TAU-72.IP",
              "from_sock" : 0,
              "to_sock" : 1
         }
     ],
    "sock" : [
        {
             "id" : 0,
             "name" : "Call Agent",
             "ipaddr" : "192.168.114.200",
             "port" : 2727,
             "transport" : "udp",
             "proto" : "mgcp",
             "profile" : 0
        },
        {
             "id" : 1,
             "name" : "TAU-72.IP",
             "ipaddr" : "192.168.114.198",
             "port" : 2427,
             "transport" : "udp",
             "proto" : "mgcp",
             "profile" : 0  
        }
    ],
    "mgcp" : [
        {
             "id" : 0,
             "mid" : "sigmgcp"
        }
    ]

}

=== alexvoipnsk/voiptest/tests/scripts/sig_megaco/iua/config.json
{
  "LogDirectory" : "/home/alexander/py_autotest/log/sigtran/",
  "Connections" : [
    {
      "id" : 0,
      "name" : "Link between Call Agent and SMG_SIGTRAN",
      "from_sock" : 0,
      "to_sock" : 1
    }
  ], 
  "sock": [ 
    {
      "id": 0,
      "name" : "Call Agent",
      "ipaddr": "192.168.114.200",
      "port": 9900,
      "transport" : "sctp",
      "proto" : "iua",
      "profile" : 0  
    },
    {
      "id": 1,
      "name" : "SMG_SIGTRAN",
      "ipaddr": "192.168.114.207",
      "port": 9900,
      "transport" : "sctp",
      "proto" : "iua",
      "profile" : 0  
    }
  ],  
  "sigtran": [
    {
      "id": 0,
      "asp": ["14"],
      "iid": ["14"]
    }
  ]
}

=== alexvoipnsk/voiptest/tests/scripts/ag_megaco/config.json
{
    "LogDirectory" : "/home/alexander/py_autotest/log/megaco/",
    "Connections" : [
         {
              "id" : 0,
              "name" : "Link between Call Agent and TAU-72.IP",
              "from_sock" : 0,
              "to_sock" : 1
         }
     ],
    "sock" : [
        {
             "id" : 0,
             "name" : "Call Agent",
             "ipaddr" : "192.168.114.200",
             "port" : 2944,
             "transport" : "udp",
             "proto" : "megaco",
             "profile" : 0
        },
        {
             "id" : 1,
             "name" : "TAU-72.IP",
             "ipaddr" : "192.168.114.199",
             "port" : 2944,
             "transport" : "udp",
             "proto" : "megaco",
             "profile" : 1  
        }
    ],
    "megaco" : [
        {
             "id" : 0,
             "mid" : "mgc",
             "encoding" : "full_text"
        },
        {
             "id" : 1,
             "mid" : "tau72m",
             "encoding" : "full_text",
             "terms" : ["p/0", "p/1"]

        }
    ]

}

=== alexvoipnsk/voiptest/tests/scripts/sig_megaco/m2ua_ets102380_sgp_one_as/config.json
{
  "LogDirectory" : "/root/voiptest/log/sigtran/",
  "Connections" : [
    {
      "id" : 0,
      "name" : "Link between Call Agent and SMG_SIGTRAN",
      "from_sock" : 0,
      "to_sock" : 1
    },
    {
      "id" : 1,
      "name" : "Link between Call Agent and SMG_SIGTRAN sec",
      "from_sock" : 2,
      "to_sock" : 3
    }
  ], 
  "sock": [ 
    {
      "id": 0,
      "name" : "Call Agent",
      "ipaddr": "192.168.114.240",
      "port": 2904,
      "transport" : "sctp",
      "proto" : "m2ua",
      "profile" : 0  
    },
    {
      "id": 1,
      "name" : "SMG_SIGTRAN",
      "ipaddr": "192.168.114.198",
      "port": 2904,
      "transport" : "sctp",
      "proto" : "m2ua",
      "profile" : 0  
    },
    {
      "id": 2,
      "name" : "Call Agent",
      "ipaddr": "192.168.114.240",
      "port": 2906,
      "transport" : "sctp",
      "proto" : "m2ua",
      "profile" : 0  
    },
    {
      "id": 3,
      "name" : "SMG_SIGTRAN sec",
      "ipaddr": "192.168.114.205",
      "port": 2904,
      "transport" : "sctp",
      "proto" : "m2ua",
      "profile" : 0  
    }
  ],  
  "sigtran": [
    {
      "id": 0,
      "asp": ["10", "11"],
      "iid": ["10", "11"] 
    }
  ]
}

=== alexvoipnsk/voiptest/tests/scripts/sip/config.json
{
  "LogDirectory" : "/home/alexander/voip_auto/voiptest/log/sigtran/",
  "Connections" : [
    {
      "id" : 0,
      "name" : "SIP trunk",
      "from_sock" : 0,
      "to_sock" : 1
    }
  ], 
  "sock": [ 
    {
      "id": 0,
      "name" : "Computer",
      "ipaddr": "192.168.114.200",
      "port": 5060,
      "transport" : "udp",
      "proto" : "megaco",
      "profile" : 0  
    },
    {
      "id": 1,
      "name" : "TAU_SIP",
      "ipaddr": "192.168.114.201",
      "port": 5060,
      "transport" : "udp",
      "proto" : "megaco",
      "profile" : 0
    }
  ],  
    "megaco" : [
    {
      "id" : 0,
      "mid" : "some_call_id_12345678"
    }
  ]
}

=== alexvoipnsk/voiptest/tests/scripts/sig_iua/config_NU.json
{
  "LogDirectory" : "/home/alexander/py_autotest/log/sigtran/",
  "Connections" : [
    {
      "id" : 0,
      "name" : "Link between Call Agent and SMG_SIGTRAN",
      "from_sock" : 0,
      "to_sock" : 1
    },
    {
      "id" : 1,
      "name" : "Link between Call Agent and MEGACO",
      "from_sock" : 2,
      "to_sock" : 3
    }
  ], 
  "sock": [ 
    {
      "id": 0,
      "name" : "SIGTRAN gateway",
      "ipaddr": "192.168.114.200",
      "port": 2913,
      "transport" : "sctp",
      "proto" : "m2ua",
      "profile" : 0  
    },
    {
      "id": 1,
      "name" : "SSW_SIGTRAN",
      "ipaddr": "192.168.116.150",
      "port": 2904,
      "transport" : "sctp",
      "proto" : "m2ua",
      "profile" : 0  
    },
    {
      "id" : 2,
      "name" : "SIGTRAN gateway",
      "ipaddr" : "192.168.114.200",
      "port" : 2946,
      "transport" : "udp",
      "proto" : "megaco",
      "profile" : 0
    },
    {
      "id" : 3,
      "name" : "SSW_MEGACO",
      "ipaddr" : "192.168.116.150",
      "port" : 2945,
      "transport" : "udp",
      "proto" : "megaco",
      "profile" : 1  
    }
  ],  
  "sigtran": [
    {
      "id": 0,
      "asp": ["12"],
      "iid": ["iid11"] 
    }
  ],
  "megaco" : [
    {
      "id" : 0,
      "mid" : "smg",
      "encoding" : "full_text"
    },
    {
      "id" : 1,
      "mid" : "ssw",
      "encoding" : "full_text"
    }
  ]
}
